### ISSUE TITLE
Possible errors

### ISSUE THREAD

**Issue by Lexikos** [zero-plusplus/ahk-include-path-resolver#7]
While looking for the cause of  zero-plusplus/vscode-autohotkey-debug#159, I have found some possible errors.

I believe [this code](https://github.com/zero-plusplus/ahk-include-path-resolver/blob/5ac63f739507da893d2c32fc7b897d3278e6b6ce/src/index.ts#L354) is intended to get a list of all library files into `libraryPathList`:
```TypeScript
    if (!recursiveInfo.currentDir) {
      libraryTypes.forEach((libraryType) => {
        recursiveInfo.libraryPathList = this.getLibraryPathList(libraryType);
      });
    }
```
However, while it probably does retrieve the content of each library (local, user and standard), the content of local and user are probably lost because `libraryPathList` is overwritten on each iteration.

[This](https://github.com/zero-plusplus/ahk-include-path-resolver/blob/5ac63f739507da893d2c32fc7b897d3278e6b6ce/src/index.ts#L340) will evidently resolve `#Include <LibName>` unconditionally from a single lib dir of the predefined libraryType (probably `local`):
```TypeScript
      filePath = `${this.getLibraryDir(this.config.libraryType!)}/${String(filePath)}.ahk`;
```
This approach will not work correctly.

The library files used by any given script can be spread across multiple directories. Which file the interpreter chooses is based on whether a file with the appropriate name *exists* in each of the Lib folders, searched in order. For a name like `A_B`, the interpreter searches for `A_B.ahk` in all three libs, and then `A.ahk` in all three libs, until a match is found.

So `#Include <X>`  could include X.ahk from one Lib, while `#Include <Y_Z>` includes either Y_Z.ahk or Y.ahk from some other Lib.

If there are multiple matches, either by filename or by prefix, only the first match is used, in this order:
  - local, full name
  - user, full name
  - standard, full name
  - local, prefix
  - user, prefix
  - standard, prefix

**Comment by zero-plusplus** [comment]
Thank you for the information.

I will fix this issue and the [relative path issue](https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/134) with the release of vscode-autohotkey-debug 1.10.0.

This project was created when I was unfamiliar with it and is very sloppily managed.

Therefore, I will recreate it in a repository of utilities for AutoHotkey when the time comes.

**Comment by zero-plusplus** [comment]
Moved to [node-autohotkey-utilities](https://github.com/zero-plusplus/node-autohotkey-utilities/tree/develop) and split/refactored the process.

So, after a while, I will archive this repository.
